// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaRestaurante.Infrastructure;

#nullable disable

namespace SistemaRestaurante.Infrastructure.Migrations
{
    [DbContext(typeof(EFCoreContext))]
    partial class EFCoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaRestaurante.Domain.Entidades.ItemPedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("PedidoId", "ProdutoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItemPedido");
                });

            modelBuilder.Entity("SistemaRestaurante.Domain.Entidades.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SistemaRestaurante.Domain.Entidades.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("Preco")
                        .HasColumnType("float");

                    b.Property<int>("SetorPreparoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SetorPreparoId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Disponivel = true,
                            Nome = "Frango Grelhado",
                            Preco = 25.899999999999999,
                            SetorPreparoId = 3
                        },
                        new
                        {
                            Id = 2,
                            Disponivel = true,
                            Nome = "Filé ao Molho",
                            Preco = 45.0,
                            SetorPreparoId = 3
                        },
                        new
                        {
                            Id = 3,
                            Disponivel = true,
                            Nome = "Suco de Laranja",
                            Preco = 8.0,
                            SetorPreparoId = 2
                        },
                        new
                        {
                            Id = 4,
                            Disponivel = true,
                            Nome = "Refrigerante",
                            Preco = 6.0,
                            SetorPreparoId = 2
                        },
                        new
                        {
                            Id = 5,
                            Disponivel = false,
                            Nome = "Prato do Dia",
                            Preco = 22.0,
                            SetorPreparoId = 3
                        });
                });

            modelBuilder.Entity("SistemaRestaurante.Domain.Entidades.Setor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Setores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Salão",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Copa",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Cozinha",
                            Tipo = 2
                        });
                });

            modelBuilder.Entity("SistemaRestaurante.Domain.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SetorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HashSenha = "$2a$12$VEYlve5PMZs6B.0WyS7O4uhwcrRexc62CNZmTp2OEthHI7ZSzH4lm",
                            Nome = "Garçon",
                            SetorId = 1
                        },
                        new
                        {
                            Id = 2,
                            HashSenha = "$2a$12$VEYlve5PMZs6B.0WyS7O4uhwcrRexc62CNZmTp2OEthHI7ZSzH4lm",
                            Nome = "Copa",
                            SetorId = 2
                        },
                        new
                        {
                            Id = 3,
                            HashSenha = "$2a$12$VEYlve5PMZs6B.0WyS7O4uhwcrRexc62CNZmTp2OEthHI7ZSzH4lm",
                            Nome = "Cozinha",
                            SetorId = 3
                        });
                });

            modelBuilder.Entity("SistemaRestaurante.Domain.Entidades.ItemPedido", b =>
                {
                    b.HasOne("SistemaRestaurante.Domain.Entidades.Pedido", null)
                        .WithMany("ItemsPedido")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRestaurante.Domain.Entidades.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaRestaurante.Domain.Entidades.Produto", b =>
                {
                    b.HasOne("SistemaRestaurante.Domain.Entidades.Setor", null)
                        .WithMany()
                        .HasForeignKey("SetorPreparoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaRestaurante.Domain.Entidades.Usuario", b =>
                {
                    b.HasOne("SistemaRestaurante.Domain.Entidades.Setor", null)
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaRestaurante.Domain.Entidades.Pedido", b =>
                {
                    b.Navigation("ItemsPedido");
                });
#pragma warning restore 612, 618
        }
    }
}
